### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by xycloops123** [biggiesmallsAG/nightHawkResponse#11]
Hello team,

I am trying to set up the ISO in a KVM environment. But it gives nginx error.

System configuration:
1. Used set-ip as given in the nighthawk script
2. Changed the static ip/ gateway/ hotname for centOS

Please advise:
![image](https://cloud.githubusercontent.com/assets/7406483/17637007/953ea6d4-6095-11e6-9fb8-aaaa058dc854.png)

**Comment by biggiesmallsAG** [comment]
HI xycloops,

Can you please zip up the logs in /opt/nighthawk/var/logs and upload them so we can look for the issue.

Regards,

Daniel

**Comment by xycloops123** [comment]
Hi Dan,

Did a fresh copy installation again and it worked.

Thanks for the quick response.

Cheers
XM
