### ISSUE TITLE
Need manual configuration of IP address

### ISSUE THREAD

**Issue by espressobeanie** [biggiesmallsAG/nightHawkResponse#21]
Good morning,

I need to manually set the IP address, gateway, DNS server, etc... for Nighthawk and the "/opt/nighthawk/bin/nighthawkctl set-ip" command isn't sufficient enough. How do I set the rest?

**Comment by roshanmaskey** [comment]
For current version, you will have to use normal Linux commands. We are looking to add some of the basic configuration change to be done via Admin UI. 

We are including this in next release.
