### ISSUE TITLE
nightHawk v1.0.3 ISO Default Login Credentials Rejected

### ISSUE THREAD

**Issue by hc970** [biggiesmallsAG/nightHawkResponse#24]
Hello Team,

Apologies if this is my own error but the default credentials of:

nighthawk
nighthawk

are rejected after booting from the 1.0.3 ISO

I noticed another user with same issue within the comments of your YouTube video: 

https://www.youtube.com/watch?v=3bHfAt8bEk8

Any advice that you may be able to provide would be much appreciated. I’m really looking forward to trying out this software, especially the interactive process tree. Thanks in advance for your time.

**Comment by roshanmaskey** [comment]
Hi hc970,

Please try nighthawk:nightHawk

**Comment by liston** [comment]
That's strange because when you look into the /etc/passwd file you see user nighthawk being directed to /sbin/nologin.

Liston

**Comment by roshanmaskey** [comment]
Liston you are correct, it is admin and nightHawk

**Comment by hc970** [comment]
@roshanmaskey You are correct. That worked (admin and nightHawk). Thank you very much. Have a great day.

nighthawk:nightHawk was rejected.
