### ISSUE TITLE
nightHawkResponse

### ISSUE THREAD

**Issue by freeman-ng** [biggiesmallsAG/nightHawkResponse#5]
Hi,
Thanks for sharing the tool.
I installed and tried to upload mans files in zip (around 550MB) but the upload failed upon several attempts.

Regards,
fn

**Comment by roshanmaskey** [comment]
Hi Freeman-ng,

It will not process Redline mans file (which is sqlite), you will have to upload zip file containing audits files. 

I have uploaded a sample file "20160707054834.zip" that our tool will process in nighthawk_utils for reference. 

Let us know if this helps.

**Comment by freeman-ng** [comment]
Hi,
It is up and running now.
Many thanks.  Good work and fast response. Two thumbs up.
