### ISSUE TITLE
Can't access from browser

### ISSUE THREAD

**Issue by kishore-negi** [biggiesmallsAG/nightHawkResponse#7]
Hi

I can't access the https://192.168.42.173 from any browser. It's showing me an error : Bad Request (400)
But I am able to access Kibana,  via; https://192.168.42.173:8443

So kindly help me to access that asap.

Thanks
Kishore

**Comment by roshanmaskey** [comment]
Hi Kishore,

I am assuming you are using v1.0.2. 

Can you restart the service using following commands
sudo systemctl stop nighthawk
sudo systemctl start nighthawk

sudo systemctl status nighthawk (should say active (exited))

Let me know if you still have error accessing the main app.

**Comment by kishore-negi** [comment]
Hi,

I have already tried this one and yes i'm using v1.0.2. But i am still facing the same error.Bad Request (400)
For your reference:

[root@nighthawk admin]#  sudo systemctl stop nighthawk
[root@nighthawk admin]# sudo systemctl start nighthawk
[root@nighthawk admin]# sudo systemctl status nighthawk
nighthawk.service - nightHawk Response Service
   Loaded: loaded (/usr/lib/systemd/system/nighthawk.service; enabled)
   Active: active (exited) since Wed 2016-07-20 23:31:18 UTC; 2s ago
  Process: 11429 ExecStop=/opt/nighthawk/bin/nighthawkctl service stop (code=exited, status=0/SUCCESS)
  Process: 11453 ExecStart=/opt/nighthawk/bin/nighthawkctl service start (code=exited, status=0/SUCCESS)
 Main PID: 11453 (code=exited, status=0/SUCCESS)

Jul 20 23:30:56 nighthawk.local systemd[1]: Starting nightHawk Response Service...
Jul 20 23:31:18 nighthawk.local systemd[1]: Started nightHawk Response Service.

**Comment by roshanmaskey** [comment]
Could you please send logs from following locations to 
-- roshanmaskey@gmail.com
-- daniel.eden@gmail.com

/var/log/nginx
/var/log/audit
/opt/nighthawk/var/log

**Comment by biggiesmallsAG** [comment]
Hi kishore-negi,

Just quickly, did you change any settings after you installed the ISO? Did the web gui work at all or it wasn't working from the start?

Regards, 

Daniel

**Comment by kishore-negi** [comment]
Hi All,

Daniel, I haven't change any settings except ip address,gateway and dns.
The web gui didn't work from the starting for the main app but i'm able to
access the Kibana on port 8443.

Below find the attached logs .

Thanks
Kishore

**Comment by roshanmaskey** [comment]
Hi Kishore,

It looks like that while changing IP address you did not use following command 
/opt/nighthawk/bin/nighthawkctl set-ip <new_ip_address> 

Application needs to change IP address at multiple location so I would suggest you to use that.

You can fix your current issue by updating IP address in following file.
/opt/nighthawk/web/nighthawk/settings.py
replace 192.168.42.173 with 192.168.104.52 in ALLOWED_HOSTS
i.e. ALLOWED_HOSTS = ['192.168.104.52','nighthawk.local']

Restart the application after saving the change.

**Comment by kishore-negi** [comment]
Thanks roshanmaskey and daniel for the help.

It's working now.

kishore

**Comment by biggiesmallsAG** [comment]
no worries kishore!
