### ISSUE TITLE
 Mandiant's  Redline tool Issue

### ISSUE THREAD

**Issue by kishore-negi** [biggiesmallsAG/nightHawkResponse#9]
Hi

I have installed NightHawk app and the Kibana tool in ubuntu. But for investigate system memory and files to discover malicious activity i want to use RedLine tool but it doen't work for ubuntu.

How I can collaborate files with the app?

Suggest me asap.

Thanks
Kishore Negi

**Comment by biggiesmallsAG** [comment]
Hi Kishore,

Redline/HX only cover Windows XP/7/8/10/server. NightHawk is purely (at this time) only for windows based forensics.

Regards,

Daniel
